### PR TITLE
add discussion repo

### PR DESCRIPTION
**Pull request by richsalz**

### CODE REVIEW

**Comment by mnot** [comment]
I don't think this is supported. Let me look into it upstream...

**Comment by richsalz** [comment]
Perhaps I'm confused.  It's not just new issue threads?

**Comment by mnot** [comment]
No, it's not issues, it's a separate mechanism.

**Comment by richsalz** [comment]
I was confused.  Sorry for the noise.  Time to look at what API they have.

**Comment by mnot** [comment]
See:
  https://github.com/dontcallmedom/github-notify-ml/issues/67

tl;dr -- it isn't currently supported in upstream, but is theoretically possible (although IIRC it currently doesn't use the GraphQL API, so this isn't a small change).

**Comment by mnot** [comment]
Closing for now.

**Pull request closed without merging**
