### PR TITLE
ADD WG update

### PR DESCRIPTION
**Pull request by gitnnelg**
updated repo name draft-ietf-add-requirements
added new draft repos for draft-ietf-add-ddr and draft-ietf-add-dnr

### CODE REVIEW

**Comment by gitnnelg** [comment]
updated ADD WG repos

**Comment by mnot** [comment]
Hi Glenn,

Would you mind pushing a small (eg whitespace) update to the PR? For some reason the checks didn't run.

**Comment by gitnnelg** [comment]
Hi Mark

I found a stray blank line in the ADD repos section and removed it, hopefully and committed.  Is that enough or do I need to kill the PR and redo it entirely?

Question -  What is ietf-github-services/issue-summary for vs. activity-summary?


glenn
On 3/15/21, 4:51 PM, "Mark Nottingham" ***@***.******@***.***>> wrote:


Hi Glenn,

Would you mind pushing a small (eg whitespace) update to the PR? For some reason the checks didn't run.

**Comment by mnot** [comment]
That worked, thanks!

**Pull request merged**
