### PR TITLE
Add ssh chartering group

### PR DESCRIPTION
**Pull request by richsalz**
thanks

### CODE REVIEW

**Comment by mnot** [comment]
Can you give the list a heads-up that you're requesting this, so it doesn't appear unilateral?

**Comment by richsalz** [comment]
Already done; SecAD approves
```
Thanks for that.  

We want it easy to make charter tweaks, but we also want to keep the mailing list in the loop.  There is a fine line we will walk here. 

Deb

On Wed, Jul 31, 2024 at 4:40 PM Salz, Rich <rsalz=[40akamai.com@dmarc.ietf.org](mailto:40akamai.com@dmarc.ietf.org)> wrote:
> I think it'd be great if you did that Rich, thanks. (I
> always forget how its done every single time I do it for
> some list:-)

I did.  First message will come through Sunday.  If consensus doesn't like it, easy to take it down.

(Make a pull request against `mls.json` in the [https://github.com/ietf-github-services/activity-summary/](https://github.com/ietf-github-services/activity-summary/ repo :)
```

**Comment by mnot** [comment]
Thanks!

**Comment by richsalz** [comment]
Au contraire, merci a vous

**Pull request merged**
